from utils.window_parameters.main_menu import MainMenuWindowParameters
from utils.window_parameters.game import GameWindowParameters
from utils.window_parameters.in_game_save import InGameSaveWindowParameters
